/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessoRouteImport } from './routes/accesso'
import { Route as SSurveyIdRouteImport } from './routes/s.$surveyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoRoute = AccessoRouteImport.update({
  id: '/accesso',
  path: '/accesso',
  getParentRoute: () => rootRouteImport,
} as any)
const SSurveyIdRoute = SSurveyIdRouteImport.update({
  id: '/s/$surveyId',
  path: '/s/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesso': typeof AccessoRoute
  '/s/$surveyId': typeof SSurveyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesso': typeof AccessoRoute
  '/s/$surveyId': typeof SSurveyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesso': typeof AccessoRoute
  '/s/$surveyId': typeof SSurveyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accesso' | '/s/$surveyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accesso' | '/s/$surveyId'
  id: '__root__' | '/' | '/accesso' | '/s/$surveyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoRoute: typeof AccessoRoute
  SSurveyIdRoute: typeof SSurveyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesso': {
      id: '/accesso'
      path: '/accesso'
      fullPath: '/accesso'
      preLoaderRoute: typeof AccessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$surveyId': {
      id: '/s/$surveyId'
      path: '/s/$surveyId'
      fullPath: '/s/$surveyId'
      preLoaderRoute: typeof SSurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoRoute: AccessoRoute,
  SSurveyIdRoute: SSurveyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
